import { ExerciseType } from '../types';

export const EXERCISE_INSTRUCTIONS: Partial<Record<ExerciseType, string>> = {
  [ExerciseType.FITB]: 'Drag a word from the word bank to fill in the blank.',
  [ExerciseType.CollocationGapFill]: 'Drag a word from the word bank to complete the collocation.',
  [ExerciseType.PhrasalVerbGapFill]: 'Drag a particle from the word bank to complete the phrasal verb.',
  [ExerciseType.MultipleChoice]: 'Select the best option to answer the question.',
  [ExerciseType.SentenceScramble]: 'Click the words in the correct order to form a sentence.',
  [ExerciseType.ClozeParagraph]: 'Use the dropdown menus to select the best word for each blank.',
  [ExerciseType.Matching]: 'Click a prompt on the left, then click its matching answer on the right.',
  [ExerciseType.ErrorCorrection]: 'Rewrite the sentence to correct the grammatical error.',
  [ExerciseType.DialogueCompletion]: 'Use the dropdown menus to select the best word for each blank in the dialogue.',
  [ExerciseType.StorySequencing]: 'Drag and drop the story parts into the correct chronological order.',
  [ExerciseType.Prediction]: 'Read the story start and select the most logical continuation.',
  [ExerciseType.RuleDiscovery]: 'Read the example sentences and choose the option that best describes the grammar rule.',
  [ExerciseType.SpotTheDifference]: 'Compare the two sentences and choose the option that best explains the difference in meaning.',
  [ExerciseType.PicturePrompt]: 'Read the scene description and write your response below.',
  [ExerciseType.MoralDilemma]: 'Read the dilemma and write your reasoned response below.',
  [ExerciseType.ProblemSolvingScenario]: 'Read the scenario and write your solution below.',
  [ExerciseType.WordFormation]: 'Type the correct form of the root word to complete the sentence.',
  [ExerciseType.ReadingGist]: 'Read the text quickly to understand the main idea, then answer the question.',
  [ExerciseType.ReadingDetail]: 'Scan the text to find the specific information needed to answer the questions.',
  [ExerciseType.FunctionalWriting]: 'Read the scenario and complete the writing task as instructed.',
  [ExerciseType.DictoGloss]: 'Read the text, then hide it and try to reconstruct it from memory in the text box below.',
  [ExerciseType.CollocationOddOneOut]: 'Select the word that does NOT form a common partnership with the keyword.',
  [ExerciseType.InformationTransfer]: 'Read the text and transfer the required information into the form fields.',
  [ExerciseType.ListeningSpecificInfo]: 'Read the transcript as if you were listening, then answer the questions.',
  [ExerciseType.RolePlayScenario]: 'Read your role and the situation, then write what you would say.',
  [ExerciseType.StorytellingFromPrompts]: 'Write a story that includes all of the given prompts.',
  [ExerciseType.JustifyYourOpinion]: 'Read the statement, then write your opinion with supporting reasons.',
  [ExerciseType.PictureComparison]: 'Read the descriptions of the two scenes, then write a comparison.',
  [ExerciseType.FunctionMatching]: 'Match the phrases on the left to their social functions on the right.',
  [ExerciseType.RegisterSort]: 'Drag each phrase into the category (e.g., Formal, Informal) where it belongs.',
  [ExerciseType.PolitenessScenarios]: 'Read the scenario and choose the most polite and appropriate response.',
  [ExerciseType.InferringMeaning]: 'Read the dialogue and choose the option that best explains the implied meaning.',
};
